/*****************************************************************************
 * Open MCT, Copyright (c) 2014-2024, United States Government
 * as represented by the Administrator of the National Aeronautics and Space
 * Administration. All rights reserved.
 *
 * Open MCT is licensed under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 * Open MCT includes source code licensed under additional open source
 * licenses. See the Open Source Licenses file (LICENSES.md) included with
 * this source code distribution or the Licensing information page available
 * at runtime from the About dialog for additional information.
 *****************************************************************************/

/*
 * Karma configuration for local development: the same specs, without the
 * work that exists to produce a CI coverage report.
 *
 * `karma.conf.cjs` loads `webpack.coverage.mjs`, which runs
 * `babel-plugin-istanbul` over every source file, emits inline source maps
 * and writes junit and lcov reports. CI needs all of that. An edit-run loop
 * needs none of it, and pays for it on every run.
 *
 * Set SPEC_FILTER to bundle only the specs you are working on. It is a
 * regular expression matched against paths like './src/utils/timeSpec.js':
 *
 *   npm run test:fast
 *   SPEC_FILTER='^\./src/utils/.*Spec\.js$' npm run test:fast
 */

const fs = require('node:fs');
const path = require('node:path');

const ROOT = __dirname;
const DEFAULT_FILTER = String.raw`^\./(src|example)/.*Spec\.js$`;
// require.context needs a literal regular expression, so the entry point is
// generated rather than reading the filter at runtime.
const ENTRY = path.join(ROOT, 'dist', 'index-test-filtered.cjs');

function writeEntry() {
  const filter = process.env.SPEC_FILTER || DEFAULT_FILTER;
  const source =
    `// Generated by karma.fast.cjs. Do not edit; dist/ is not tracked.\n` +
    `const specs = require.context('../', true, /${filter.replace(/\//g, '\\/')}/);\n` +
    `specs.keys().forEach(specs);\n`;

  fs.mkdirSync(path.dirname(ENTRY), { recursive: true });
  fs.writeFileSync(ENTRY, source);
}

module.exports = async (config) => {
  writeEntry();

  const webpackConfig = (await import('./.webpack/webpack.dev.mjs')).default;
  delete webpackConfig.output;
  delete webpackConfig.entry; // Karma doesn't support webpack entry

  config.set({
    basePath: '',
    frameworks: ['jasmine', 'webpack'],
    files: [
      'dist/index-test-filtered.cjs',
      // Not included via <script>: the shared worker source has to be
      // loaded remotely by the shared worker process.
      { pattern: 'dist/couchDBChangesFeed.js*', included: false },
      { pattern: 'dist/inMemorySearchWorker.js*', included: false },
      { pattern: 'dist/generatorWorker.js*', included: false },
      { pattern: 'dist/historicalTelemetryWorker.js*', included: false }
    ],
    preprocessors: { 'dist/index-test-filtered.cjs': ['webpack'] },
    reporters: ['spec'],
    specReporter: {
      maxLogLines: 5,
      suppressErrorSummary: false,
      suppressFailed: false,
      suppressPassed: true,
      suppressSkipped: true,
      showSpecTiming: true,
      failFast: false
    },
    browsers: ['ChromeHeadless'],
    client: { jasmine: { random: false, timeoutInterval: 6000 } },
    colors: true,
    logLevel: config.LOG_INFO,
    webpack: webpackConfig,
    webpackMiddleware: { stats: 'errors-only' },
    concurrency: 1,
    singleRun: true,
    autoWatch: false,
    browserNoActivityTimeout: 400000
  });
};
